dataset_root: /ocean/projects/cis250019p/gandotra/11785-gp-eeg
metadata_csv: data/processed/metadata.csv
train_split_csv: data/splits/train.csv
val_split_csv: data/splits/val.csv
test_split_csv: data/splits/test.csv

model_name: eegnet_baseline
num_classes: 20
num_channels: 122
num_timesteps: 500
dropout: 0.25
temporal_filters: 16
depth_multiplier: 2
separable_filters: 32
embedding_dim: 256
projection_dim: 256
projection_hidden_dim: 256
projection_dropout: 0.1
normalize_projected_embedding: true

batch_size: 64
num_workers: 4
lr: 0.001
weight_decay: 0.0001
epochs: 30
normalization: zscore_per_channel_trainset
label_smoothing: 0.0
scheduler: none
seed: 42
device: cuda

output_dir: outputs

wandb:
  enabled: true
  entity: yejc20
  project: eeg-task1
  run_name: null
  mode: online
